server:
  port: 8090

spring:
  config:
    import: "optional:configserver:"
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@userKeyResolver}"

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@userKeyResolver}"

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@userKeyResolver}"

        - id: payment-service
          uri: http://localhost:3001/api/mock # lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@userKeyResolver}"

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@userKeyResolver}"

        - id: eureka-registry-mock
          uri: http://localhost:3001
          predicates:
            - Path=/eureka/apps
          # Direct proxy for Eureka monitor mapping during mock phase

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
